"""Initial migration

Revision ID: 8d0c5364e97f
Revises: 
Create Date: 2023-10-26 12:25:33.251713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0c5364e97f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=25), nullable=False),
    sa.Column('bookauthor', sa.String(length=25), nullable=False),
    sa.Column('year_published', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('BookID')
    )
    op.create_table('customers',
    sa.Column('CustID', sa.Integer(), nullable=False),
    sa.Column('CustName', sa.String(length=25), nullable=False),
    sa.Column('City', sa.String(length=25), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('CustID')
    )
    op.create_table('loans',
    sa.Column('LoanID', sa.Integer(), nullable=False),
    sa.Column('CustID', sa.Integer(), nullable=False),
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('LoanDate', sa.DateTime(), nullable=False),
    sa.Column('ReturnDate', sa.DateTime(), nullable=True),
    sa.Column('LoanType', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BookID'], ['books.BookID'], ),
    sa.ForeignKeyConstraint(['CustID'], ['customers.CustID'], ),
    sa.PrimaryKeyConstraint('LoanID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('customers')
    op.drop_table('books')
    # ### end Alembic commands ###
