"""Add MaxReturnDate column to loans

Revision ID: d5c8fa3728ce
Revises: 8d0c5364e97f
Create Date: 2023-10-26 15:24:51.409567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c8fa3728ce'
down_revision = '8d0c5364e97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaxReturnDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('MaxReturnDate')

    # ### end Alembic commands ###
